export type XOAITextContentPart = { type: 'text'; text: string };
export type XOAIImageContentPart = {
  type: 'image_url';
  image_url: {
    /**
     * @description Either a URL of the image or the base64 encoded image data.
     */
    url: string;
  };
};
export type XOAIAudioContentPart = { type: 'input_audio'; input_audio: { data: string } };
export type XOAIVideoContentPart = {
  type: 'video_url';
  video_url: {
    /**
     * @description Either a URL of the video or the base64 encoded video data.
     */
    url: string;
  };
  /**
   * @description Number of frames sampled per second.
   * @required Range: [0.1, 10.0]
   * @default 2
   */
  fps: number;
  /**
   * @description Resolution level.
   * Available options: default, max
   * @default 'default'
   */
  media_resolution: 'default' | 'max';
};

export type XOAIToolCall = {
  /**
   * The function that the model called.
   */
  function: {
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    arguments: string;
    /**
     * The name of the function to call.
     */
    name: string;
  };
  /**
   * The ID of the tool call.
   */
  id: string;
  /**
   * Tool type. Currently, only function is supported.
   */
  type: 'function';
};

export type XOAIDeveloperMessage = {
  /**
   * @description Available options: developer
   */
  role: 'developer';
  /**
   * @description An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;
  /**
   * @description The contents of the developer message.
   */
  content: string | XOAITextContentPart[];
};

export type XOAISystemMessage = {
  /**
   * @description Role of the message author. Available options: system
   */
  role: 'system';
  /**
   * @description An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;
  /**
   * @description The contents of the system message.
   */
  content: string | XOAITextContentPart[];
};

export type XOAIUserMessage = {
  /**
   * @description Role of the message author. Available options: user
   */
  role: 'user';
  /**
   * @description An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;
  /**
   * @description The contents of the user message.
   *
   */
  content:
    | string
    | (XOAITextContentPart | XOAIImageContentPart | XOAIAudioContentPart | XOAIVideoContentPart)[];
};

export type XOAIAssistantMessage = {
  /**
   * @description Role of the message author. Available options: assistant
   */
  role: 'assistant';
  /**
   * @description An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;
  /**
   * @description The contents of the assistant message. Required unless tool_calls is specified.
   *
   */
  content?: string | XOAITextContentPart[];
  /**
   * @description The tool calls generated by the model, such as function calls.
   */
  tool_calls?: XOAIToolCall[];
};

export type XOAIToolMessage = {
  /**
   * @description Role of the message author. Available options: tool
   */
  role: 'tool';
  /**
   * @description The contents of the tool message.
   *
   */
  content?: string | XOAITextContentPart[];
  /**
   * @description Tool call that this message is responding to.
   */
  tool_call_id: string[];
};

export type XOAIModal =
  | 'mimo-v2.5-pro'
  | 'mimo-v2.5'
  | 'mimo-v2.5-tts'
  | 'mimo-v2.5-tts-voicedesign'
  | 'mimo-v2.5-tts-voiceclone'
  | 'mimo-v2-pro'
  | 'mimo-v2-omni'
  | 'mimo-v2-tts'
  | 'mimo-v2-flash';

export type XOAIMessage =
  | XOAIDeveloperMessage
  | XOAISystemMessage
  | XOAIUserMessage
  | XOAIAssistantMessage
  | XOAIToolMessage;

export type XOAIRequestAudio = {
  /**
   * Specifies the output audio format. Default: wav, or pcm when you set stream: true.
   *
   * Passing in pcm or pcm16 both indicate specifying the use of the pcm16 format.
   *
   * Available options: wav, mp3, pcm, pcm16
   * @default 'wav'
   */
  format?: 'wav' | 'mp3' | 'pcm' | 'pcm16';
  /**
   * Enables intelligent optimization of the target audio broadcast text.
   *
   * When set to true, the input target text is intelligently polished; if no target text is provided, a broadcast-adapted target text is automatically generated. The finalized processed text is then fed into the model for speech synthesis.
   *
   * Note: When this parameter is set to true, the assistant role message for specifying speech synthesis content can be omitted.
   *
   * Currently, only the mimo-v2.5-tts-voicedesign model is supported.
   *
   * @default false
   */
  optimize_text_preview?: boolean;
  /**
   * The voice ID of the built-in voice or the base64 encoding of the audio sample.
   * mimo-v2.5-tts, mimo-v2-tts: This field is optional and only supports using built-in voices, with the default value being mimo_default
   *
   * mimo-v2.5-tts-voiceclone: This field is required and only supports passing in the base64 encoding of audio samples, and only supports passing in audio sample files in mp3 and wav formats
   *
   * mimo-v2.5-tts-voicedesign does not support this field
   *
   * Available options:
   *
   * mimo-v2-tts: mimo_default, default_en, default_zh
   *
   * mimo-v2.5-tts: mimo_default, 冰糖, 茉莉, 苏打, 白桦, Mia, Chloe, Milo, Dean
   */
  voice?: string;
};

export type XOAIRequestThinking = {
  /**
   * Whether to enable the chain of thought.
   *
   * mimo-v2-flash: default disabled
   *
   * mimo-v2.5-pro, mimo-v2.5, mimo-v2-pro, mimo-v2-omni: default enabled
   *
   * Available options: enabled, disabled
   */
  type: 'enabled' | 'disabled';
};

export type XOAIResponseFormat =
  | {
      /**
       * Default response format. Used to generate text responses.
       *
       * The type of response format being defined. Always "text".
       */
      type: 'text';
    }
  | {
      /**
       * JSON object response format. Note that the model will not generate JSON without a system or user message instructing it to do so.
       *
       * The type of response format being defined. Always "json_object".
       */
      type: 'json_object';
    };

/**
 * A function tool that can be used to generate a response.
 */
export type XOAIFunctionTool = {
  /**
   * Tool type. Currently, only function is supported.
   */
  type: 'function';
  function: {
    /**
     * The name of the tool function. Must be a-z, A-Z, 0-9, or contain underscores (_) and dashes (-), with a maximum length of 64.
     *
     * Required string length: 1 - 64
     */
    name: string;
    /**
     * A description of what the function does, used by the model to choose when and how to call the function.
     */
    description?: string;
    /**
     * The parameters the functions accept, described as a JSON Schema object.
     *
     * Omitting parameters defines a function with an empty parameter list.
     */
    parameters?: Record<string, unknown>;

    /**
     * Whether to enable strict schema adherence when generating the function call.
     *
     * If set to true, the model will follow the exact schema defined in the parameters field.
     *
     * Only a subset of JSON Schema is supported when strict is true.
     *
     * @default false
     */
    strict?: boolean;
  };
};

export type XOAIRequestBody = {
  /**
   * The current conversation message list.
   */
  messages: XOAIMessage[];
  /**
   * Model ID is used to generate the response.
   * Available options: mimo-v2.5-pro, mimo-v2.5, mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone, mimo-v2-pro, mimo-v2-omni, mimo-v2-tts, mimo-v2-flash
   */
  model: XOAIModal;
  /**
   * Parameters for audio output. For details, please refer to Speech Synthesis.
   * @see https://platform.xiaomimimo.com/#/docs/usage-guide/speech-synthesis-v2.1
   *
   * Note: To generate audio, you must add a message with role set to assistant, which needs to specify the text for speech synthesis.
   *
   * Additionally, when using the mimo-v2.5-tts-voicedesign model, a message with the role of user is required.
   *
   * If optimize_text_preview is set to true, the assistant message can be omitted. For detailed usage, please refer to Speech Synthesis.
   *
   * Currently, only the mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone and mimo-v2-tts models are supported.
   */
  audio?: XOAIRequestAudio;
  /**
   * Number between -2.0 and 2.0.
   *
   * Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
   *
   * Required range: [-2.0, 2.0]
   */
  frequency_penalty?: number | null;
  /**
   * An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens.
   *
   * mimo-v2-flash: default 65536
   *
   * mimo-v2.5-pro, mimo-v2-pro: default 131072
   *
   * mimo-v2.5, mimo-v2-omni: default 32768
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voiceclone, mimo-v2.5-tts-voicedesign, mimo-v2-tts: default 8192, required range is [1, 8192]
   *
   * Required range: [1, 131072]
   */
  max_completion_tokens?: number | null;
  /**
   * Number between -2.0 and 2.0.
   *
   * Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
   *
   * Required range: [-2.0, 2.0]
   */
  presence_penalty?: number | null;
  /**
   * An object specifying the format that the model must output.
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone and mimo-v2-tts models are not supported.
   */
  response_format?: XOAIResponseFormat;
  /**
   * Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone and mimo-v2-tts models are not supported.
   *
   * @default null
   */
  stop?: string | string[] | null;
  /**
   * If set to true, the model response data will be streamed to the client as it is generated using server-sent events.
   *
   * @default false
   */
  stream?: boolean | null;
  /**
   * This parameter is used to control whether the model enables the chain of thought.
   *
   * Note: During the multi-turn tool calls process in thinking mode, the model returns a reasoning_content field alongside tool_calls. To continue the conversation, it is recommended to keep all previous reasoning_content in the messages array for each subsequent request to achieve the best performance.
   *
   * In thinking mode, the mimo-v2.5-pro and mimo-v2.5 models do not support customizing the temperature parameter. Even if this parameter is passed in, it will be forcibly overridden and take effect with the model's recommended default value of 1.0.
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone and mimo-v2-tts models are not supported.
   */
  thinking?: XOAIRequestThinking;
  /**
   * What sampling temperature to use, between 0 and 1.5. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.
   *
   * In thinking mode, the mimo-v2.5-pro and mimo-v2.5 models do not support customizing the temperature parameter. Even if this parameter is passed in, it will be forcibly overridden and take effect with the model's recommended default value of 1.0.
   *
   * mimo-v2-flash: default 0.3
   *
   * mimo-v2.5-pro, mimo-v2.5, mimo-v2-pro, mimo-v2-omni: default 1.0
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voiceclone, mimo-v2.5-tts-voicedesign, mimo-v2-tts: default 0.6
   *
   * Required range: [0, 1.5]
   */
  temperature?: number;
  /**
   * Controls how the model selects a tool.
   *
   * Note: When a value other than auto is passed to tool_choice, the backend will remove this field by default, and the model response behavior will still be equivalent to the auto mode (this logic is subject to future adjustments).
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone and mimo-v2-tts models are not supported.
   *
   * Available options: auto
   */
  tool_choice?: 'auto';
  /**
   * A list of tools the model may call. You can provide function tools.
   *
   * Note: During the multi-turn tool calls process in thinking mode, the model returns a reasoning_content field alongside tool_calls. To continue the conversation, it is recommended to keep all previous reasoning_content in the messages array for each subsequent request to achieve the best performance.
   *
   * mimo-v2.5-tts, mimo-v2.5-tts-voicedesign, mimo-v2.5-tts-voiceclone and mimo-v2-tts models are not supported.
   */
  tools?: XOAIFunctionTool[];
  /**
   * The probability threshold for nucleus sampling, which controls the diversity of the text that the model generates.
   *
   * A higher top_p value results in more diverse text. A lower top_p value results in more deterministic text.
   *
   * Because both temperature and top_p control the diversity of the generated text, we recommend that you set only one of them.
   *
   * Required range: [0.01, 1.0]
   */
  top_p?: number;
};
